# Generated by Django 3.2.13 on 2022-11-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_path',
            field=models.TextField(null=True),
        ),
    ]
