# Generated by Django 3.2.13 on 2022-11-21 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='article',
            new_name='articles',
        ),
    ]
