# Generated by Django 3.2.13 on 2022-11-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_path',
            field=models.TextField(default='https://emojigraph.org/media/microsoft/honeybee_1f41d.png'),
        ),
    ]
