# Generated by Django 3.2.13 on 2022-11-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_path',
            field=models.TextField(default='https://postfiles.pstatic.net/MjAyMjExMjNfMjc2/MDAxNjY5MTgyODM0NDk0.2DzAP8o4F2XRV3Hf295K_RMSesfO9H4pPSXi1yvE9r4g.vk_yk3LEq_HOiTa48qK-gS6qqByQCGd-xqNiuBpKp-4g.PNG.qsc130/basic_profile.png?type=w966'),
        ),
    ]
