# Generated by Django 3.2.13 on 2022-11-21 06:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='user',
            name='reported',
            field=models.ManyToManyField(related_name='reporting', to=settings.AUTH_USER_MODEL),
        ),
    ]
