# Generated by Django 3.2.13 on 2022-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221121_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stopped',
            field=models.DateTimeField(null=True),
        ),
    ]
