# Generated by Django 3.2.13 on 2022-11-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_path',
            field=models.TextField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGTscNJlgpTAHrwG6kBOgIN10pNW3RX35ByBdzxwQExmQ5-Y_HQq_gMJEdDn8Jc9DIDyA&usqp=CAU'),
        ),
    ]
