# Generated by Django 3.2.13 on 2022-11-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_stopped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stopped',
        ),
    ]
